### ISSUE TITLE
Import of multiple excel rows/columns

### ISSUE THREAD

**Issue by namahato** [Jochen-Kall/Safety_concept_tool#12]
While copying (Ctrl + C) multiple rows/columns from excel and pesting (Ctrl + V) into mind map tool, It creats the new nodes in a table box view. This table view do not show up the FRS and ASIL  completely. How can we copy pest multiple rows from excel into mind map tool?

**Comment by Jochen-Kall** [comment]
Hi Naveen,

easiest method to import a range of spreadsheet cells is to use ctrl + shift + v and select "Plain text as node hierarchy".
Much more powerful importer for .csv files that allows importing arbitrary collumns into the various fields is under development and coming soon.
